language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t tiagoreichert/redirect-collabserv .
  - docker run -d -p 127.0.0.1:80:80 --name redirect-collabserv tiagoreichert/redirect-collabserv

script:
  - docker ps | grep -q redirect-collabserv

